### ISSUE TITLE
Customers functionality

### ISSUE THREAD

**Issue by jollopre** [jollopre/mps#24]
Steven is going to pass me the list of customers so that we have to create a script that populates the table customers in the database.

**Comment by marshallpack1974** [comment]
I will send the customer list and supplier list next week.

**Comment by jollopre** [comment]
Three tasks have to done at three levels:
- At server: Creating customers controller with at least index action
- At client: View to display the list of customers and link to her/his orders associated.
- Scripting: Creating a bash script to load CSV file provided and load the data into the database
