### ISSUE TITLE
Paginate views

### ISSUE THREAD

**Issue by jollopre** [jollopre/mps#29]
The following view lists must be paginated:
- Customers
- Orders

otherwise, this will not scale when the db has a considerable amount of results. NOTE, this will not be delivered as part of the MVP.

**Comment by marshallpack1974** [comment]
Please elaborate...what extra cost is involved?

Thanks
Steven Marshall

**Comment by jollopre** [comment]
The resources customers and orders have been paginated as follows:

- At the server-side, it has been installed two gems (e.g. kaminari-core and kaminari-activerecord), and updated the actions customers#index and orders#index accordingly.
- At the client-side, it has been created an own sub-state (e.g. pagination to handle each resource, actions and reducers to handle cached pages and currentPage, a higher-order reducer to drive to the appropriate resource when queried, and an agnostic presentational component for showing previous/next for each resource)
